### ISSUE TITLE
Models not closing once action completed (new patient, new practitioner, recording activity)

### ISSUE THREAD

**Issue by Nicca42** [RibbonBlockchain/IncentivesMVP#31]
# Models not closing once action completed
Usability Bug - Medium

When creating a patient, practitioner or recording an activity, the model stays open once the information has been saved. At best this is an irritation, at worst it could result in multiple records of the same information as it does not clearly indicate that the saving/processing was successful. 

## Acceptance criteria
- [x] After creating and saving a new patient, the model is hidden
- [x] After creating and saving a new practitioner the model is hidden
- [x] After recording a patient activity the model is hidden

![image.png](https://images.zenhubusercontent.com/5d41f6db9b341d33444331ff/773357c9-9e28-4b69-9566-8cf4358ecea7)

**Comment by KapsonLabs** [comment]
#37 fixes this issue.
